language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - pypy
  - pypy3
install:
  - pip install -e .
  - pip install codecov
script:
  - coverage run setup.py test
  - coverage report -m
after_script:
  codecov
