language: python
python:
  - "2.7"
  - "3.4"
install:
  - pip install -e .
  - pip install coveralls
  - pip install coverage
  - pip install nose
script:
  - coverage run --source=port_range setup.py test
  - coverage report -m
after_script:
  coveralls --verbose
